### ISSUE TITLE
roleSchemaDef uses incorrect mongoose modeling

### ISSUE THREAD

**Issue by eacaps** [bluehalo/node-rest-starter#209]
`roleSchemaDef` defines an object with in the type field. the contents of this object will be ignored and the `roles` field will default to a blank object. Changes should be made to properly create the roles field as a nested object.

**Comment by jrassa** [comment]
Needs to be verified, but I think this may have been resolved by the upgrade to Mongoose 6 (#200).

https://mongoosejs.com/docs/migrating_to_6.html#typepojotomixed

**Comment by eacaps** [comment]
After testing it out it seems the defaults were still not being added until I changed it to a nested object: https://github.com/bluehalo/node-rest-starter/pull/210/files#r968571329

**Comment by eacaps** [comment]
After seeing some weirdness in the audit log:
```
[2022-09-15T13:55:42.206Z]  INFO: audit/42161 on ecapito: message created
    audit: {
      "type": "message",
      "action": "create",
      "actor": {
        "_id": "631f939431403d9b0c3864c5",
        "name": "admin",
        "username": "admin",
        "organization": "something",
        "email": "eacaps@gmail.com",
        "phone": "",
        "messagesAcknowledged": 0,
        "alertsViewed": "2022-09-12T20:20:38.980Z",
        "newFeatureDismissed": null,
        "canProxy": false,
        "canMasquerade": false,
        "roles": "[Throws: Cannot read properties of undefined (reading 'paths')]",
        "bypassAccessCheck": false,
        "teams": []
      },
      "object": {
        "type": "MOTD",
        "title": "dafdsa",
        "body": "fdafda",
        "ackRequired": false,
        "created": "2022-09-15T13:55:42.185Z",
        "updated": "2022-09-15T13:55:42.185Z",
        "_id": "63232edeb4157fcc719d6f7d"
      },
      "userAgent": {
        "browser": "Chrome 104.0.0.0",
        "os": "OS X 10.15.7 64-bit"
      }
    }
```
note the roles field resolves to: ` "roles": "[Throws: Cannot read properties of undefined (reading 'paths')]",`. I did a little digging and apparently the roles field is now a nested object and for some reason that does not like doing `_.cloneDeep`. Prior to the fix I made for this issue apparently mongo was treating `roles` as a subdocument so I went ahead and made changes to turn it back into a proper subdocument:
```
[2022-09-15T14:25:15.952Z]  INFO: audit/47383 on ecapito: message created
    audit: {
      "type": "message",
      "action": "create",
      "actor": {
        "_id": "631f939431403d9b0c3864c5",
        "name": "admin",
        "username": "admin",
        "organization": "something",
        "email": "eacaps@gmail.com",
        "phone": "",
        "messagesAcknowledged": 0,
        "alertsViewed": 1663014038980,
        "newFeatureDismissed": null,
        "canProxy": false,
        "canMasquerade": false,
        "roles": {
          "_id": "632335cb3b645cc728abb50a",
          "user": true,
          "admin": true,
          "auditor": false,
          "editor": false
        },
        "bypassAccessCheck": false,
        "teams": []
      },
      "object": {
        "type": "MOTD",
        "title": "fdafdas",
        "body": "dafdsafa",
        "ackRequired": false,
        "created": 1663251915930,
        "updated": 1663251915931,
        "_id": "632335cb3b645cc728abb50b"
      },
      "userAgent": {
        "browser": "Chrome 104.0.0.0",
        "os": "OS X 10.15.7 64-bit"
      }
    }
```
